/**
 * Vite plugin that:
 * 1. Generates `src/components/avatar/styles/index.ts` — a module with
 *    `STYLE_NAMES` array, lazy `import()` map, and cached `loadStyle()`.
 * 2. Generates `public/heads.svg` — an SVG sprite sheet with one avatar
 *    preview per style (used by the style bar instead of dynamic imports).
 */
import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

import type { Plugin } from 'vite'

const _require = createRequire(import.meta.url)

/* ─── Helpers ─────────────────────────────────────── */

/**
 * Generate the styles module content.
 * @param names
 * @returns TypeScript source string.
 */
function generateModule(names: string[]): string {
  const imports = names
    .map((n) => `  '${n}': () => import('@dicebear/styles/${n}.json'),`)
    .join('\n')

  return [
    '/* prettier-ignore-start */',
    '/**',
    ' * Auto-generated by vite-plugin-dicebear-styles. Do not edit.',
    ' *',
    ' * Exposes all available DiceBear v10 style names and lazy-loading helpers.',
    ' */',
    "import { Style } from '@dicebear/core';",
    '',
    `export const STYLE_NAMES = ${JSON.stringify(names)};`,
    '',
    'const definitions: Record<string, () => Promise<{ default: object }>> = {',
    imports,
    '};',
    '',
    'const cache = new Map<string, Style>();',
    '',
    'export async function loadStyle(name: string): Promise<Style> {',
    '  const cached = cache.get(name);',
    '  if (cached) {',
    '    return cached;',
    '  }',
    '',
    '  const loader = definitions[name];',
    '  if (!loader) {',
    '    throw new Error(`DiceBear style "${name}" not found`);',
    '  }',
    '',
    '  const mod = await loader();',
    '  const style = new Style(mod.default);',
    '  cache.set(name, style);',
    '  return style;',
    '}',
    '/* prettier-ignore-end */',
    '',
  ].join('\n')
}

/**
 * Generate SVG symbols for each style (used in sprite sheet).
 * @param styleNames
 * @returns SVG symbol elements joined by newline.
 */
function generateSpriteSymbols(styleNames: string[]): string {
  const { Avatar, Style } = _require('@dicebear/core')
  const parts: string[] = []

  for (const name of styleNames) {
    try {
      const json = _require(`@dicebear/styles/${name}.json`)
      const style = new Style(json)
      const avatar = new Avatar(style, { seed: name, size: 40 })
      const svg = avatar.toString()

      const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 280 280'
      const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
      const id = name.replace(/[^a-zA-Z0-9-]/g, '-')

      parts.push(`  <symbol id="${id}" viewBox="${viewBox}">${inner}</symbol>`)
    } catch (err) {
      console.warn(`[dicebear-styles] Failed to generate sprite for "${name}": ${err}`)
    }
  }

  return parts.join('\n')
}

/**
 * Write the SVG sprite sheet to public/heads.svg.
 * @param names
 */
function writeSprite(names: string[]): void {
  const spritePath = path.resolve('public/heads.svg')
  const symbols = generateSpriteSymbols(names)
  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols}\n</svg>\n`

  if (fs.existsSync(spritePath)) {
    const existing = fs.readFileSync(spritePath, 'utf-8')
    if (existing === sprite) {
      return
    }
  }

  fs.mkdirSync(path.dirname(spritePath), { recursive: true })
  fs.writeFileSync(spritePath, sprite, 'utf-8')
}

/**
 * Parse @dicebear/styles/package.json exports to extract style names.
 * @returns Sorted array of style name strings.
 */
function discoverStyles(): string[] {
  const pkgPath = path.resolve('node_modules/@dicebear/styles/package.json')
  const raw = fs.readFileSync(pkgPath, 'utf-8')
  const pkg = JSON.parse(raw) as { exports?: Record<string, unknown> }

  const names = new Set<string>()
  if (pkg.exports) {
    for (const key of Object.keys(pkg.exports)) {
      if (key === './package.json') {
        continue
      }
      const match = key.match(/^\.\/(.+)\.json$/)
      if (match) {
        names.add(match[1])
      }
    }
  }
  return [...names].sort()
}

/* ─── Plugin ──────────────────────────────────────── */

/**
 * Vite plugin for DiceBear style module + SVG sprite sheet generation.
 * @returns Vite plugin instance.
 */
export function dicebearStylesPlugin(): Plugin {
  const outputPath = path.resolve('src/components/avatar/styles/index.ts')

  return {
    name: 'vite-plugin-dicebear-styles',
    buildStart() {
      const names = discoverStyles()

      // 1. Write lazy-loading styles module
      const code = generateModule(names)
      if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, 'utf-8') !== code) {
        fs.mkdirSync(path.dirname(outputPath), { recursive: true })
        fs.writeFileSync(outputPath, code, 'utf-8')
        console.log(`[dicebear-styles] Generated styles module (${names.length} styles)`)
      }

      // 2. Generate SVG sprite sheet for the style bar
      writeSprite(names)
    },
  }
}
