/**
 * Vite plugin that generates `src/components/avatar/dicebear-styles.ts`
 * by scanning all style JSON exports from `@dicebear/styles/package.json`.
 *
 * Outputs a `STYLE_NAMES` array, lazy `import()` map, and a cached `loadStyle()`.
 */
import fs from 'node:fs'
import path from 'node:path'

import type { Plugin } from 'vite'

/** Generate the styles module content from a list of style names.
 *
 * @param names
 * @returns Generated TypeScript source string for the styles module.
 */
function generateModule(names: string[]): string {
  const exportLines = names.map((n) => `  '${n}': () => import('@dicebear/styles/${n}.json'),`)

  return `/* prettier-ignore-start */
/**
 * Auto-generated by vite-plugin-dicebear-styles. Do not edit.
 *
 * Exposes all available DiceBear v10 style names and lazy-loading helpers.
 */
import { Style } from '@dicebear/core';

export const STYLE_NAMES = ${JSON.stringify(names)};

const definitions: Record<string, () => Promise<{ default: object }>> = {
${exportLines.join('\n')}
};

const cache = new Map<string, Style>();

export async function loadStyle(name: string): Promise<Style> {
  const cached = cache.get(name);
  if (cached) {
    return cached;
  }

  const loader = definitions[name];
  if (!loader) {
    throw new Error(\`DiceBear style "\${name}" not found\`);
  }

  const mod = await loader();
  const style = new Style(mod.default);
  cache.set(name, style);
  return style;
}
/* prettier-ignore-end */
`
}

/**
 * Parse `@dicebear/styles/package.json` exports to extract style names.
 * Each export is `./{name}.json`.
 *
 * @returns Sorted array of style name strings.
 */
function discoverStyles(): string[] {
  const pkgPath = path.resolve('node_modules/@dicebear/styles/package.json')
  const raw = fs.readFileSync(pkgPath, 'utf-8')
  const pkg = JSON.parse(raw) as { exports?: Record<string, unknown> }

  const names = new Set<string>()
  if (pkg.exports) {
    for (const key of Object.keys(pkg.exports)) {
      if (key === './package.json') {
        continue
      }
      const match = key.match(/^\.\/(.+)\.json$/)
      if (match) {
        names.add(match[1])
      }
    }
  }
  return [...names].sort()
}

/**
 *
 * @returns Vite plugin instance.
 */
export function dicebearStylesPlugin(): Plugin {
  const outputPath = path.resolve('src/components/avatar/styles/index.ts')

  return {
    name: 'vite-plugin-dicebear-styles',
    /** Generate the module at build start and when dev server restarts. */
    buildStart() {
      const names = discoverStyles()
      const code = generateModule(names)

      // Only write if content changed (avoid unnecessary HMR)
      if (fs.existsSync(outputPath)) {
        const existing = fs.readFileSync(outputPath, 'utf-8')
        if (existing === code) {
          return
        }
      }

      fs.mkdirSync(path.dirname(outputPath), { recursive: true })
      fs.writeFileSync(outputPath, code, 'utf-8')
      console.log(`[dicebear-styles] Generated with ${names.length} styles`)
    },
  }
}
