/**
 * Vite plugin that:
 * 1. Generates `src/components/avatar/styles.ts` — a module with
 *    `STYLE_NAMES` array, lazy `import()` map, and cached `loadStyle()`.
 * 2. Generates `public/header.svg` — an SVG sprite sheet with one avatar
 *    preview per style (used by the style bar instead of dynamic imports).
 */
import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'

import type { Plugin } from 'vite'

const _require = createRequire(import.meta.url)

/* ─── Helpers ─────────────────────────────────────── */

/**
 * Parse @dicebear/styles/package.json exports to extract style names.
 * @returns Sorted array of style name strings.
 */
function discoverStyles(): string[] {
  const pkgPath = path.resolve('node_modules/@dicebear/styles/package.json')
  const raw = fs.readFileSync(pkgPath, 'utf-8')
  const pkg = JSON.parse(raw) as { exports?: Record<string, unknown> }

  const names = new Set<string>()
  if (pkg.exports) {
    for (const key of Object.keys(pkg.exports)) {
      if (key === './package.json') {
        continue
      }
      const match = key.match(/^\.\/(.+)\.json$/)
      if (match) {
        names.add(match[1])
      }
    }
  }
  return [...names].sort()
}

/**
 * Generate the styles module content.
 * @param names
 * @returns TypeScript source string.
 */
function generateModule(names: string[]): string {
  const imports = names
    .map((n) => `  '${n}': () => import('@dicebear/styles/${n}.json'),`)
    .join('\n')

  return [
    '/* eslint-disable */',
    '',
    '/**',
    ' * Auto-generated by vite-plugin-dicebear-styles. Do not edit.',
    ' *',
    ' * Exposes all available DiceBear v10 style names and lazy-loading helpers.',
    ' */',
    "import { Style } from '@dicebear/core';",
    '',
    `export const STYLE_NAMES = ${JSON.stringify(names)};`,
    '',
    'const definitions: Record<string, () => Promise<{ default: object }>> = {',
    imports,
    '};',
    '',
    'const cache = new Map<string, Style>();',
    '',
    'export async function loadStyle(name: string): Promise<Style> {',
    '  const cached = cache.get(name);',
    '  if (cached) {',
    '    return cached;',
    '  }',
    '',
    '  const loader = definitions[name];',
    '  if (!loader) {',
    '    throw new Error(`DiceBear style "${name}" not found`);',
    '  }',
    '',
    '  const mod = await loader();',
    '  const style = new Style(mod.default);',
    '  cache.set(name, style);',
    '  return style;',
    '}',
    '',
  ].join('\n')
}

/**
 * Generate SVG sprite sheet for each style.
 * @param styleNames
 * @returns Full SVG sprite sheet string.
 */
function generateSprite(styleNames: string[]): string {
  const { Avatar, Style } = _require('@dicebear/core')
  const parts: string[] = []

  for (const name of styleNames) {
    try {
      const json = _require(`@dicebear/styles/${name}.json`)
      const style = new Style(json)
      const avatar = new Avatar(style, { seed: name, size: 40 })
      const svg = avatar.toString()

      const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 280 280'
      const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
      const id = name.replace(/[^a-zA-Z0-9-]/g, '-')

      parts.push(`  <symbol id="${id}" viewBox="${viewBox}">${inner}</symbol>`)
    } catch (err) {
      console.warn(`[dicebear-styles] Failed to generate sprite for "${name}": ${err}`)
    }
  }

  return [
    '<!-- Auto-generated by vite-plugin-dicebear-styles. Do not edit. -->',
    '',
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
    parts.join('\n'),
    '</svg>',
    '',
  ].join('\n')
}

/**
 * Write content to file if it differs from existing content.
 * Skips write when content is unchanged to avoid unnecessary rebuilds.
 * @param filePath - Target file path.
 * @param fileContent - Content to write.
 */
function write(filePath: string, fileContent: string): void {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf-8')
    if (existing === fileContent) {
      return
    }
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, fileContent, 'utf-8')
}

/* ─── Plugin ──────────────────────────────────────── */

/**
 * Vite plugin for DiceBear style module + SVG sprite sheet generation.
 * @returns Vite plugin instance.
 */
export function dicebearStylesPlugin(): Plugin {
  return {
    name: 'vite-plugin-dicebear-styles',
    buildStart() {
      const names = discoverStyles()

      // 1. Write lazy-loading styles module
      const modulePath = path.resolve('src/generated/dicebear-styles.ts')
      const module = generateModule(names)
      write(modulePath, module)

      // 2. Write SVG sprite sheet for the style bar
      const spritePath = path.resolve('src/generated/dicebear-header.svg')
      const sprite = generateSprite(names)
      write(spritePath, sprite)
    },
  }
}
